### ISSUE TITLE
Cerebrate HW requirements: Bad link and missing info

### ISSUE THREAD

**Issue by ghost** [melicertes/docs#7]
The link to the HW requirements of cerebrate used here is:
https://github.com/cerebrate-project/cerebrate/blob/main/README.md#requirements-and-installation
but should be https://github.com/cerebrate-project/cerebrate/blob/main/README.md#user-content-requirements-and-installation

And the linked section says nothing about disk space, both for the native installation as well as for the docker installation method (which is additionally not linked the installation section).

**Comment by iglocska** [comment]
Done, though the link looks fine to me.
